#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:
  
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#find the sum of the even-valued terms.

fib <- function(n){
  fib <- rep(NA,n)
  fib[1] <- 1
  fib[2] <- 2
  for(i in 3:n){
    fib[i] <- fib[i-1] + fib[i-2]
  }
  return(fib[fib<n])
}

fibo <- function(n){
  b = 1
  a = 0
  my_fib = c()
  i = 1
  while(a < n){
    my_fib <- append( my_fib, a )
    temp1 = a
    temp2 = b
    a = b
    b = temp1 + temp2
    i =i+1
  }
  #return(c(0, my_fib[my_fib != 0]))
  return(my_fib)
}
options(digits=22)
#check which 
system.time(x <- fib(4e6))
system.time(x1 <- fibo(4e6))
x1 <- fibo(4e6)
y=x[which(x%%2==0)]

sum(y)==4613732